plugins {
    id 'java'
    id 'info.solidsoft.pitest' version '1.19.0-rc.2'
}

group = "com.github.mslowiak"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

pitest {
    junit5PluginVersion = '1.2.2'
    pitestVersion = '1.18.2'

    targetClasses = ['com.github.mslowiak.pricing.*']
    targetTests = ['com.github.mslowiak.*']
    outputFormats = ['HTML', 'XML']
    timestampedReports = false
}

tasks.test {
    useJUnitPlatform()
}